{% set name = "gmpacket" %}
{% set version = "0.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gmpacket-{{ version }}.tar.gz
  sha256: 749b83b82425a1bf8f0d9c49ee1d5e2061d6d0a5c1b08651f6e89fa9b796734a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=42
    - wheel
    - setuptools-scm >=3.4
    - cython >=0.29.23
    - numpy
    - pip
  run:
    - python >=3.8
    - geopy >=2.1.0
    - pandas >=1.4.0
    - pydantic >=2.0
    # this is probably wrong, I'll check upstream why it was added
    - setuptools-scm >=6.3.2

test:
  imports:
    - gmpacket
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/SCEDC/ground-motion-packet
  summary: ANSS Ground Motion Packet
  license: Unicode-DFS-2016
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - ocefpaf
