{% set name = "gmpacket" %}
{% set version = "0.1.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gmpacket-{{ version }}.tar.gz
  sha256: bfa5bdb36fb73334209ce0f8acaf45973f45cef2b439016d4b396f0249949790

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - wheel
    - setuptools-scm >=3.4
    - cython >=0.29.23
    - numpy
    - pip
  run:
    - python >={{ python_min }}
    - geopy >=2.1.0
    - pandas >=1.4.0
    - pydantic >=2.0
    # this is probably wrong, I'll check upstream why it was added
    - setuptools-scm >=6.3.2

test:
  imports:
    - gmpacket
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/SCEDC/ground-motion-packet
  summary: ANSS Ground Motion Packet
  license: Unicode-DFS-2016
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - ocefpaf
